CREATE TABLE animals (
    id serial,
  name varchar,
  weight numeric CHECK (weight > 0)
);

-- данный код выведет в ошибку
INSERT INTO animals (name, weight) VALUES 
('Pepa', -10);

CREATE TABLE animals (
    id serial,
  name varchar,
  weight numeric CONSTRAINT weight_must_be_positive CHECK (weight > 0)
);

-- данный код выведет в ошибку
INSERT INTO animals (name, weight) VALUES 
('Pepa', -10);

-- пройдет условие - не вызовет ошибку
INSERT INTO animals (name, weight) VALUES 
('Pepa', 200);

-- 
CREATE TABLE vehicles (
  id serial PRIMARY KEY,
  model VARCHAR NOT NULL,
  max_speed int
);

-- данный код вызовет ошибку 
INSERT INTO vehicles (max_speed) 
VALUES 
(30);

CREATE TABLE dress (
   id serial NOT NULL,
   title text NOT NULL,
   price numeric,
   CONSTRAINT dress_must_be_unique UNIQUE(title)
);

INSERT INTO dress (title, price) VALUES 
('channel white flower', 600);

-- ЧТО ВМЕСТО можно указать вместо SERIAL 
-- Всегда генерируется базой данных:
-- GENERATED ALWAYS AS IDENTITY PRIMARY KEY

-- Генерируется базой - если ничего не указали, 
-- а если указали - то будет использоваться тот ид, который вы указали
-- GENERATED BY DEFAULT PRIMARY KEY

CREATE TABLE account (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  balance numeric NOT NULL CHECK (balance > 0)
);

-- EXPLAIN
-- EXPLAIN ANALYZE 
-- перед запросом указываете - и получаете информацию про запрос


explain analyze SELECT
  COUNT(*)
FROM
  farmers
WHERE
  country IN ('USA', 'UK', 'Spain');
